### ISSUE TITLE
[UI][Desktop]: Overflow image cover the dropdown menu.

### ISSUE THREAD

**Issue by Ahmed-M-Osman1** [ahmedsomaa/picloom#3]
## Issue Description:
On Desktop, If the image dimensions are big enough it will cover the dropdown menu.

## Expected behaviour: 
the image should not cover the dropdown menu.

## System Spic: 
- Windows 11.22.
- Chrome: Version 123.0.6312.86 (Official Build) (64-bit).
- used image:
![433960335_1568908367202819_2905755718132736279_n](https://github.com/ahmedsomaa/picloom/assets/64021350/eb77b966-b352-4ec9-8ca2-48644f6b7c2b)

## Reproduce step: 
- Open [sharpstudio](https://sharpstudio.vercel.app/).
- Upload photo (example photo provided).
- See the overflow and overlap.

## ScreenShot: 
![image](https://github.com/ahmedsomaa/picloom/assets/64021350/092b1c06-cae1-440c-92e3-d9392a66206e)

**Comment by ahmedsomaa** [comment]
@Ahmed-M-Osman1 Couldn't reproduce on any of the tools. 
![Screenshot 2024-03-31 at 00-10-03 Screenshot](https://github.com/ahmedsomaa/picloom/assets/29373629/27e704be-910e-43e0-b44d-75d532dd1cdf)
![Screenshot 2024-03-31 at 00-09-48 Screenshot](https://github.com/ahmedsomaa/picloom/assets/29373629/5671f6c3-271a-46e3-9ed4-38432c80bee0)
![Screenshot 2024-03-31 at 00-09-31 Screenshot](https://github.com/ahmedsomaa/picloom/assets/29373629/377098f1-4332-480e-bb3e-f246536d51de)

**Comment by MinaSameh1** [comment]
Couldn't reproduce. Even when zoomed in
![image](https://github.com/ahmedsomaa/picloom/assets/47836846/54d5f1a4-879c-41ad-a306-83c8222cb195)
